baseURL = 'https://df.id.au/'
title = 'df.id.au'
theme = 'PaperMod'

# Not used anywhere in this site's content.
disableKinds = ['taxonomy', 'term']

[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  env = 'production'
  defaultTheme = 'dark'
  ShowToc = true
  ShowBreadCrumbs = true
  ShowShareButtons = false

  [params.assets]
    favicon = 'favicon.png'
    favicon16x16 = 'favicon.png'
    favicon32x32 = 'favicon.png'
    apple_touch_icon = 'favicon.png'

  [params.label]
    icon = 'images/head.jpeg'
