export const workouts = [
    {
        date: '2020-09-17',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 12100,
        workTime: 1440,
        restTime: 0,
        calories: 336,
    },
    {
        date: '2020-09-19',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 0,
        workTime: 360,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-09-20',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'Rower',
        distance: 7200,
        workTime: 1800,
        restTime: 0,
        calories: 460,
    },
    {
        date: '2020-09-22',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 810,
        restTime: 810,
        calories: 313,
    },
    {
        date: '2020-09-23',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 2100,
        workTime: 437,
        restTime: 450,
        calories: 164,
    },
    {
        date: '2020-09-24',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 2200,
        workTime: 540,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-09-25',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15200,
        workTime: 1800,
        restTime: 0,
        calories: 422,
    },
    {
        date: '2020-09-29',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4300,
        workTime: 900,
        restTime: 600,
        calories: 326,
    },
    {
        date: '2020-09-30',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 3900,
        workTime: 960,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-01',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18100,
        workTime: 2160,
        restTime: 0,
        calories: 497,
    },
    {
        date: '2020-10-03',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 3700,
        workTime: 900,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-04',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22400,
        workTime: 2700,
        restTime: 0,
        calories: 608,
    },
    {
        date: '2020-10-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'SkiErg',
        distance: 4000,
        workTime: 900,
        restTime: 900,
        calories: 272,
    },
    {
        date: '2020-10-07',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 21000,
        workTime: 2520,
        restTime: 0,
        calories: 576,
    },
    {
        date: '2020-10-09',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '2.5k',
        workTime: 480,
        restTime: 960,
        calories: 210,
    },
    {
        date: '2020-10-10',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 5800,
        workTime: 720,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-11',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 5500,
        workTime: 720,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-13',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 6200,
        workTime: 660,
        restTime: 660,
        calories: 237,
    },
    {
        date: '2020-10-17',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 7300,
        workTime: 960,
        restTime: 0,
        calories: 219,
    },
    {
        date: '2020-10-18',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 4900,
        workTime: 600,
        restTime: 0,
        calories: 154,
    },
    {
        date: '2020-10-20',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4800,
        workTime: 1080,
        restTime: 360,
        calories: 343,
    },
    {
        date: '2020-10-21',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 11900,
        workTime: 1440,
        restTime: 0,
        calories: 388,
    },
    {
        date: '2020-10-23',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 17000,
        workTime: 2100,
        restTime: 0,
        calories: 542,
    },
    {
        date: '2020-10-24',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 900,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-25',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: 4600,
        workTime: 600,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-10-27',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 14900,
        workTime: 1800,
        restTime: 0,
        calories: 489,
    },
    {
        date: '2020-10-28',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 540,
        restTime: 600,
        calories: 0,
    },
    {
        date: '2020-10-30',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: 6800,
        workTime: 720,
        restTime: 720,
        calories: 263,
    },
    {
        date: '2020-10-31',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 4800,
        workTime: 600,
        restTime: 0,
        calories: 150,
    },
    {
        date: '2020-11-01',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'BikeErg',
        distance: 11900,
        workTime: 1200,
        restTime: 240,
        calories: 385,
    },
    {
        date: '2020-11-03',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 19300,
        workTime: 2400,
        restTime: 0,
        calories: 612,
    },
    {
        date: '2020-11-04',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 17600,
        workTime: 2160,
        restTime: 0,
        calories: 568,
    },
    {
        date: '2020-11-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 1900,
        workTime: 360,
        restTime: 720,
        calories: 171,
    },
    {
        date: '2020-11-07',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 8700,
        workTime: 1080,
        restTime: 0,
        calories: 278,
    },
    {
        date: '2020-11-08',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'BikeErg',
        distance: 16000,
        workTime: 1920,
        restTime: 0,
        calories: 529,
    },
    {
        date: '2020-11-10',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4500,
        workTime: 900,
        restTime: 900,
        calories: 376,
    },
    {
        date: '2020-11-11',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 20400,
        workTime: 2520,
        restTime: 0,
        calories: 653,
    },
    {
        date: '2020-11-13',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 4800,
        workTime: 495,
        restTime: 660,
        calories: 188,
    },
    {
        date: '2020-11-14',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 6000,
        workTime: 750,
        restTime: 0,
        calories: 191,
    },
    {
        date: '2020-11-15',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: 13400,
        workTime: 1440,
        restTime: 0,
        calories: 367,
    },
    {
        date: '2020-11-17',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21800,
        workTime: 2700,
        restTime: 0,
        calories: 697,
    },
    {
        date: '2020-11-18',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 3500,
        workTime: 720,
        restTime: 720,
        calories: 277,
    },
    {
        date: '2020-11-20',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 11800,
        workTime: 1440,
        restTime: 0,
        calories: 381,
    },
    {
        date: '2020-11-21',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 720,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-11-22',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: 0,
        workTime: 360,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-11-24',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15100,
        workTime: 1800,
        restTime: 0,
        calories: 417,
    },
    {
        date: '2020-11-25',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 2500,
        workTime: 540,
        restTime: 540,
        calories: 0,
    },
    {
        date: '2020-11-27',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4800,
        workTime: 1050,
        restTime: 600,
        calories: 347,
    },
    {
        date: '2020-11-28',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 5700,
        workTime: 720,
        restTime: 0,
        calories: 178,
    },
    {
        date: '2020-11-29',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: 13000,
        workTime: 1440,
        restTime: 0,
        calories: 355,
    },
    {
        date: '2020-11-30',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22000,
        workTime: 2700,
        restTime: 0,
        calories: 707,
    },
    {
        date: '2020-12-02',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18200,
        workTime: 2160,
        restTime: 0,
        calories: 509,
    },
    {
        date: '2020-12-05',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: 4000,
        workTime: 480,
        restTime: 0,
        calories: 91,
    },
    {
        date: '2020-12-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 2700,
        workTime: 540,
        restTime: 540,
        calories: 218,
    },
    {
        date: '2020-12-08',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 20300,
        workTime: 2520,
        restTime: 0,
        calories: 648,
    },
    {
        date: '2020-12-09',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 2600,
        workTime: 480,
        restTime: 960,
        calories: 229,
    },
    {
        date: '2020-12-16',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 6700,
        workTime: 720,
        restTime: 720,
        calories: 250,
    },
    {
        date: '2020-12-17',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: 0,
        workTime: 1440,
        restTime: 0,
        calories: 459,
    },
    {
        date: '2020-12-19',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 5800,
        workTime: 720,
        restTime: 0,
        calories: 0,
    },
    {
        date: '2020-12-20',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 17000,
        workTime: 2100,
        restTime: 0,
        calories: 545,
    },
    {
        date: '2020-12-22',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3900,
        workTime: 844,
        restTime: 480,
        calories: 217,
    },
    {
        date: '2020-12-23',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 14800,
        workTime: 1800,
        restTime: 0,
        calories: 411,
    },
    {
        date: '2020-12-26',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 3500,
        workTime: 720,
        restTime: 720,
        calories: 279,
    },
    {
        date: '2020-12-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: 6300,
        workTime: 680,
        restTime: 280,
        calories: 240,
    },
    {
        date: '2020-12-28',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'AirDyne',
        distance: 11000,
        workTime: 780,
        restTime: 360,
        calories: 248,
    },
    {
        date: '2020-12-30',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 2000,
        workTime: 385,
        restTime: 660,
        calories: 166,
    },
    {
        date: '2021-01-01',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 10600,
        workTime: 1200,
        restTime: 300,
        calories: 374,
    },
    {
        date: '2021-01-01',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 20300,
        workTime: 2700,
        restTime: 0,
        calories: 567,
    },
    {
        date: '2021-01-02',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3400,
        workTime: 720,
        restTime: 690,
        calories: 255,
    },
    {
        date: '2021-01-03',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18100,
        workTime: 2160,
        restTime: 0,
        calories: 500,
    },
    {
        date: '2021-01-05',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 771,
        restTime: 660,
        calories: 279,
    },
    {
        date: '2021-01-08',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 4600,
        workTime: 981,
        restTime: 705,
        calories: 344,
    },
    {
        date: '2021-01-09',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 21100,
        workTime: 2520,
        restTime: 0,
        calories: 581,
    },
    {
        date: '2021-01-10',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: 12700,
        workTime: 1440,
        restTime: 360,
        calories: 450,
    },
    {
        date: '2021-01-11',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 6200,
        workTime: 720,
        restTime: 360,
        calories: 232,
    },
    {
        date: '2021-01-12',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: 9000,
        workTime: 1020,
        restTime: 480,
        calories: 317,
    },
    {
        date: '2021-01-14',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3800,
        workTime: 900,
        restTime: 480,
        calories: 285,
    },
    {
        date: '2021-01-16',
        phase: 'Hybrid',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: 1900,
        workTime: 2700,
        restTime: 0,
        calories: 60,
    },
    {
        date: '2021-01-17',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21700,
        workTime: 2700,
        restTime: 0,
        calories: 693,
    },
    {
        date: '2021-01-19',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 16100,
        workTime: 1980,
        restTime: 0,
        calories: 521,
    },
    {
        date: '2021-01-20',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3900,
        workTime: 825,
        restTime: 525,
        calories: 308,
    },
    {
        date: '2021-01-23',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 6500,
        workTime: 1440,
        restTime: 480,
        calories: 465,
    },
    {
        date: '2021-01-24',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: 4000,
        workTime: 400,
        restTime: 450,
        calories: 166,
    },
    {
        date: '2021-01-25',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18200,
        workTime: 2160,
        restTime: 0,
        calories: 508,
    },
    {
        date: '2021-01-26',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21900,
        workTime: 2700,
        restTime: 0,
        calories: 705,
    },
    {
        date: '2021-01-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 630,
        restTime: 510,
        calories: 233,
    },
    {
        date: '2021-01-28',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 2500,
        workTime: 495,
        restTime: 495,
        calories: 206,
    },
    {
        date: '2021-01-29',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21800,
        workTime: 2704,
        restTime: 0,
        calories: 700,
    },
    {
        date: '2021-02-01',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 760,
        restTime: 585,
        calories: 270,
    },
    {
        date: '2021-02-02',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 19900,
        workTime: 2340,
        restTime: 0,
        calories: 563,
    },
    {
        date: '2021-02-03',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 2300,
        workTime: 480,
        restTime: 435,
        calories: 173,
    },
    {
        date: '2021-02-05',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 5300,
        workTime: 1200,
        restTime: 300,
        calories: 374,
    },
    {
        date: '2021-02-06',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 25300,
        workTime: 1800,
        restTime: 0,
        calories: 420,
    },
    {
        date: '2021-02-08',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'AirDyne',
        distance: 15700,
        workTime: 720,
        restTime: 480,
        calories: 260,
    },
    {
        date: '2021-02-09',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 21300,
        workTime: 2520,
        restTime: 0,
        calories: 596,
    },
    {
        date: '2021-02-10',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3100,
        workTime: 630,
        restTime: 810,
        calories: 249,
    },
    {
        date: '2021-02-13',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 2300,
        workTime: 480,
        restTime: 480,
        calories: 174,
    },
    {
        date: '2021-02-15',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 2500,
        workTime: 520,
        restTime: 570,
        calories: 201,
    },
    {
        date: '2021-02-17',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22600,
        workTime: 2700,
        restTime: 0,
        calories: 624,
    },
    {
        date: '2021-02-19',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 840,
        restTime: 900,
        calories: 317,
    },
    {
        date: '2021-02-20',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: 11000,
        workTime: 1260,
        restTime: 180,
        calories: 385,
    },
    {
        date: '2021-02-21',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18200,
        workTime: 2160,
        restTime: 0,
        calories: 510,
    },
    {
        date: '2021-02-23',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 760,
        restTime: 480,
        calories: 272,
    },
    {
        date: '2021-02-25',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21900,
        workTime: 2700,
        restTime: 0,
        calories: 708,
    },
    {
        date: '2021-02-26',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 19700,
        workTime: 2340,
        restTime: 0,
        calories: 546,
    },
    {
        date: '2021-02-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 5400,
        workTime: 1170,
        restTime: 705,
        calories: 405,
    },
    {
        date: '2021-02-28',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 7800,
        workTime: 876,
        restTime: 900,
        calories: 281,
    },
    {
        date: '2021-03-03',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3400,
        workTime: 720,
        restTime: 810,
        calories: 263,
    },
    {
        date: '2021-03-05',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 2800,
        workTime: 560,
        restTime: 765,
        calories: 227,
    },
    {
        date: '2021-03-06',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21800,
        workTime: 2700,
        restTime: 0,
        calories: 698,
    },
    {
        date: '2021-03-07',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 6500,
        workTime: 1440,
        restTime: 720,
        calories: 467,
    },
    {
        date: '2021-03-08',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 18100,
        workTime: 2160,
        restTime: 0,
        calories: 500,
    },
    {
        date: '2021-03-10',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3300,
        workTime: 690,
        restTime: 480,
        calories: 248,
    },
    {
        date: '2021-03-12',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 21200,
        workTime: 2520,
        restTime: 0,
        calories: 587,
    },
    {
        date: '2021-03-14',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 740,
        restTime: 675,
        calories: 277,
    },
    {
        date: '2021-03-15',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21900,
        workTime: 2700,
        restTime: 0,
        calories: 701,
    },
    {
        date: '2021-03-17',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 3200,
        workTime: 720,
        restTime: 360,
        calories: 239,
    },
    {
        date: '2021-03-21',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 5200,
        workTime: 1140,
        restTime: 690,
        calories: 386,
    },
    {
        date: '2021-03-23',
        phase: 'Devour',
        theme: 'Time Trial',
        apparatus: 'Rower',
        distance: 2800,
        workTime: 600,
        restTime: 0,
        calories: 203,
    },
    {
        date: '2021-03-24',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4500,
        workTime: 1080,
        restTime: 240,
        calories: 336,
    },
    {
        date: '2021-03-26',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22200,
        workTime: 2700,
        restTime: 0,
        calories: 723,
    },
    {
        date: '2021-03-27',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4300,
        workTime: 960,
        restTime: 480,
        calories: 309,
    },
    {
        date: '2021-03-30',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4600,
        workTime: 1170,
        restTime: 360,
        calories: 295,
    },
    {
        date: '2021-04-02',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 900,
        restTime: 150,
        calories: 290,
    },
    {
        date: '2021-04-03',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20100,
        workTime: 2400,
        restTime: 0,
        calories: 544,
    },
    {
        date: '2021-04-04',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 5500,
        workTime: 1200,
        restTime: 600,
        calories: 403,
    },
    {
        date: '2021-04-05',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 13000,
        workTime: 1440,
        restTime: 0,
        calories: 352,
    },
    {
        date: '2021-04-07',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4800,
        workTime: 1560,
        restTime: 240,
        calories: 483,
    },
    {
        date: '2021-04-08',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15100,
        workTime: 1800,
        restTime: 0,
        calories: 417,
    },
    {
        date: '2021-04-09',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 5300,
        workTime: 1200,
        restTime: 240,
        calories: 381,
    },
    {
        date: '2021-04-10',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21900,
        workTime: 2700,
        restTime: 0,
        calories: 707,
    },
    {
        date: '2021-04-13',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4800,
        workTime: 1080,
        restTime: 360,
        calories: 355,
    },
    {
        date: '2021-04-14',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4800,
        workTime: 1080,
        restTime: 240,
        calories: 345,
    },
    {
        date: '2021-04-15',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 12900,
        workTime: 1440,
        restTime: 0,
        calories: 349,
    },
    {
        date: '2021-04-16',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 2800,
        workTime: 630,
        restTime: 90,
        calories: 198,
    },
    {
        date: '2021-04-17',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 20100,
        workTime: 2400,
        restTime: 0,
        calories: 555,
    },
    {
        date: '2021-04-18',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 5300,
        workTime: 1200,
        restTime: 240,
        calories: 368,
    },
    {
        date: '2021-04-21',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 2500,
        workTime: 545,
        restTime: 120,
        calories: 181,
    },
    {
        date: '2021-04-22',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15000,
        workTime: 1800,
        restTime: 0,
        calories: 413,
    },
    {
        date: '2021-04-23',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 3800,
        workTime: 830,
        restTime: 600,
        calories: 282,
    },
    {
        date: '2021-04-24',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22600,
        workTime: 2700,
        restTime: 0,
        calories: 619,
    },
    {
        date: '2021-04-26',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: 8400,
        workTime: 960,
        restTime: 480,
        calories: 293,
    },
    {
        date: '2021-04-27',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 5300,
        workTime: 1260,
        restTime: 360,
        calories: 381,
    },
    {
        date: '2021-04-29',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20000,
        workTime: 2400,
        restTime: 0,
        calories: 554,
    },
    {
        date: '2021-04-30',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 6300,
        workTime: 1650,
        restTime: 300,
        calories: 380,
    },
    {
        date: '2021-05-01',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 5500,
        workTime: 1200,
        restTime: 600,
        calories: 408,
    },
    {
        date: '2021-05-02',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'BikeErg',
        distance: 12000,
        workTime: 1440,
        restTime: 0,
        calories: 401,
    },
    {
        date: '2021-05-04',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 6000,
        workTime: 1440,
        restTime: 180,
        calories: 420,
    },
    {
        date: '2021-05-05',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15200,
        workTime: 1800,
        restTime: 0,
        calories: 426,
    },
    {
        date: '2021-05-06',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22400,
        workTime: 2700,
        restTime: 0,
        calories: 603,
    },
    {
        date: '2021-05-07',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 5100,
        workTime: 1200,
        restTime: 480,
        calories: 379,
    },
    {
        date: '2021-05-08',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 6400,
        workTime: 1440,
        restTime: 480,
        calories: 451,
    },
    {
        date: '2021-05-11',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 5000,
        workTime: 1200,
        restTime: 240,
        calories: 343,
    },
    {
        date: '2021-05-12',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 4200,
        workTime: 975,
        restTime: 225,
        calories: 294,
    },
    {
        date: '2021-05-14',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 12500,
        workTime: 1440,
        restTime: 0,
        calories: 355,
    },
    {
        date: '2021-05-18',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20100,
        workTime: 2400,
        restTime: 0,
        calories: 556,
    },
    {
        date: '2021-05-19',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 3700,
        workTime: 810,
        restTime: 270,
        calories: 274,
    },
    {
        date: '2021-05-21',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 7600,
        workTime: 2340,
        restTime: 360,
        calories: 538,
    },
    {
        date: '2021-05-22',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20100,
        workTime: 2400,
        restTime: 0,
        calories: 555,
    },
    {
        date: '2021-05-23',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 900,
        restTime: 300,
        calories: 291,
    },
    {
        date: '2021-05-24',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22100,
        workTime: 2700,
        restTime: 0,
        calories: 720,
    },
    {
        date: '2021-05-25',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4900,
        workTime: 1080,
        restTime: 360,
        calories: 354,
    },
    {
        date: '2021-05-28',
        phase: 'Devour',
        theme: 'Descending Devour',
        apparatus: 'Rower',
        distance: 3100,
        workTime: 720,
        restTime: 300,
        calories: 0,
    },
    {
        date: '2021-05-29',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 5000,
        workTime: 1080,
        restTime: 720,
        calories: 366,
    },
    {
        date: '2021-05-30',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: 4900,
        workTime: 1080,
        restTime: 240,
        calories: 361,
    },
    {
        date: '2021-05-31',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15100,
        workTime: 1800,
        restTime: 0,
        calories: 420,
    },
    {
        date: '2021-06-02',
        phase: 'Devour',
        theme: 'Descending Devour',
        apparatus: 'Rower',
        distance: 3200,
        workTime: 720,
        restTime: 360,
        calories: 235,
    },
    {
        date: '2021-06-04',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 8300,
        workTime: 960,
        restTime: 0,
        calories: 239,
    },
    {
        date: '2021-06-05',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 17200,
        workTime: 2100,
        restTime: 0,
        calories: 555,
    },
    {
        date: '2021-06-06',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4500,
        workTime: 900,
        restTime: 900,
        calories: 372,
    },
    {
        date: '2021-06-07',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 20000,
        workTime: 2400,
        restTime: 0,
        calories: 656,
    },
    {
        date: '2021-06-08',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 5100,
        workTime: 1170,
        restTime: 90,
        calories: 360,
    },
    {
        date: '2021-06-10',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 15000,
        workTime: 1800,
        restTime: 0,
        calories: 418,
    },
    {
        date: '2021-06-12',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 4700,
        workTime: 1050,
        restTime: 150,
        calories: 336,
    },
    {
        date: '2021-06-15',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 3300,
        workTime: 720,
        restTime: 315,
        calories: 244,
    },
    {
        date: '2021-06-16',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 5300,
        workTime: 1175,
        restTime: 360,
        calories: 382,
    },
    {
        date: '2021-06-18',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 10200,
        workTime: 1200,
        restTime: 0,
        calories: 289,
    },
    {
        date: '2021-06-21',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: 2200,
        workTime: 479,
        restTime: 180,
        calories: 93,
    },
    {
        date: '2021-06-23',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22300,
        workTime: 2700,
        restTime: 0,
        calories: 601,
    },
    {
        date: '2021-06-25',
        phase: 'Infinity',
        theme: 'Time Trial',
        apparatus: 'Rower',
        distance: 2800,
        workTime: 600,
        restTime: 0,
        calories: 205,
    },
    {
        date: '2021-06-26',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 12400,
        workTime: 1440,
        restTime: 0,
        calories: 355,
    },
    {
        date: '2021-07-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 1000,
        workTime: 245,
        restTime: 0,
        calories: 77,
    },
    {
        date: '2021-07-02',
        phase: 'Infinity',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: 12600,
        workTime: 1440,
        restTime: 480,
        calories: 443,
    },
    {
        date: '2021-07-03',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 5500,
        workTime: 1260,
        restTime: 195,
        calories: 243,
    },
    {
        date: '2021-07-04',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22300,
        workTime: 2700,
        restTime: 0,
        calories: 600,
    },
    {
        date: '2021-07-07',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 5400,
        workTime: 1200,
        restTime: 450,
        calories: 324,
    },
    {
        date: '2021-07-08',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 300,
        restTime: 300,
        calories: 126,
    },
    {
        date: '2021-07-10',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20400,
        workTime: 2400,
        restTime: 0,
        calories: 579,
    },
    {
        date: '2021-07-12',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4300,
        workTime: 982,
        restTime: 180,
        calories: 241,
    },
    {
        date: '2021-07-13',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 21800,
        workTime: 2700,
        restTime: 0,
        calories: 698,
    },
    {
        date: '2021-07-14',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 843,
        restTime: 720,
        calories: 264,
    },
    {
        date: '2021-07-15',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 12500,
        workTime: 1440,
        restTime: 0,
        calories: 367,
    },
    {
        date: '2021-07-16',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22300,
        workTime: 2700,
        restTime: 0,
        calories: 732,
    },
    {
        date: '2021-07-17',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 9000,
        workTime: 1010,
        restTime: 195,
        calories: 316,
    },
    {
        date: '2021-07-18',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3200,
        workTime: 780,
        restTime: 465,
        calories: 244,
    },
    {
        date: '2021-07-20',
        phase: 'Infinity',
        theme: 'Intervals',
        apparatus: 'SkiErg',
        distance: 3600,
        workTime: 810,
        restTime: 810,
        calories: 240,
    },
    {
        date: '2021-07-22',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 840,
        restTime: 840,
        calories: 317,
    },
    {
        date: '2021-07-24',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 20000,
        workTime: 2400,
        restTime: 0,
        calories: 565,
    },
    {
        date: '2021-07-25',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 5000,
        workTime: 1350,
        restTime: 465,
        calories: 294,
    },
    {
        date: '2021-07-29',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 5000,
        workTime: 1560,
        restTime: 450,
        calories: 391,
    },
    {
        date: '2021-08-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3900,
        workTime: 840,
        restTime: 285,
        calories: 296,
    },
    {
        date: '2021-08-04',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4200,
        workTime: 1110,
        restTime: 450,
        calories: 321,
    },
    {
        date: '2021-08-05',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 1700,
        workTime: 360,
        restTime: 360,
        calories: 128,
    },
    {
        date: '2021-08-06',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22500,
        workTime: 2700,
        restTime: 0,
        calories: 614,
    },
    {
        date: '2021-08-08',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 2600,
        workTime: 540,
        restTime: 180,
        calories: 198,
    },
    {
        date: '2021-08-09',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 9200,
        workTime: 1080,
        restTime: 0,
        calories: 266,
    },
    {
        date: '2021-08-11',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 945,
        restTime: 225,
        calories: 293,
    },
    {
        date: '2021-08-13',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 23000,
        workTime: 2700,
        restTime: 0,
        calories: 651,
    },
    {
        date: '2021-08-15',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4000,
        workTime: 840,
        restTime: 570,
        calories: 309,
    },
    {
        date: '2021-08-17',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: 25300,
        workTime: 3000,
        restTime: 0,
        calories: 703,
    },
    {
        date: '2021-08-18',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: 8000,
        workTime: 1890,
        restTime: 630,
        calories: 545,
    },
    {
        date: '2021-08-19',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 23000,
        workTime: 2700,
        restTime: 0,
        calories: 645,
    },
    {
        date: '2021-08-21',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3700,
        workTime: 780,
        restTime: 405,
        calories: 291,
    },
    {
        date: '2021-08-22',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 3600,
        workTime: 760,
        restTime: 480,
        calories: 273,
    },
    {
        date: '2021-08-24',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: 16500,
        workTime: 1920,
        restTime: 0,
        calories: 472,
    },
    {
        date: '2021-08-25',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3800,
        workTime: 810,
        restTime: 405,
        calories: 292,
    },
    {
        date: '2021-08-26',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22800,
        workTime: 2700,
        restTime: 0,
        calories: 632,
    },
    {
        date: '2021-08-29',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 22500,
        workTime: 2700,
        restTime: 0,
        calories: 613,
    },
    {
        date: '2021-08-30',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 961,
        restTime: 180,
        calories: 154,
    },
    {
        date: '2021-08-31',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 4100,
        workTime: 420,
        restTime: 420,
        calories: 165,
    },
    {
        date: '2021-09-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4700,
        workTime: 1320,
        restTime: 225,
        calories: 358,
    },
    {
        date: '2021-09-02',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: 16400,
        workTime: 1920,
        restTime: 0,
        calories: 462,
    },
    {
        date: '2021-09-04',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22100,
        workTime: 2700,
        restTime: 0,
        calories: 619,
    },
    {
        date: '2021-09-06',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3700,
        workTime: 1200,
        restTime: 165,
        calories: 278,
    },
    {
        date: '2021-09-07',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: 5500,
        workTime: 1170,
        restTime: 765,
        calories: 414,
    },
    {
        date: '2021-09-09',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: 27400,
        workTime: 3300,
        restTime: 0,
        calories: 907,
    },
    {
        date: '2021-09-11',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 22700,
        workTime: 2700,
        restTime: 0,
        calories: 759,
    },
    {
        date: '2021-09-14',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 3000,
        workTime: 900,
        restTime: 405,
        calories: 241,
    },
    {
        date: '2021-09-15',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: 3600,
        workTime: 780,
        restTime: 390,
        calories: 259,
    },
    {
        date: '2021-09-16',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: 7600,
        workTime: 1800,
        restTime: 0,
        calories: 513,
    },
    {
        date: '2021-09-17',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 4300,
        workTime: 1279,
        restTime: 450,
        calories: 237,
    },
    {
        date: '2021-09-19',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'BikeErg',
        distance: 12100,
        workTime: 1443,
        restTime: 0,
        calories: 405,
    },
    {
        date: '2021-09-23',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: 2500,
        workTime: 600,
        restTime: 345,
        calories: 196,
    },
];
