export const workouts = [
    {
        date: '2020-09-17',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '12.11km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 336,
    },
    {
        date: '2020-09-19',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '0:00:00',
        workTime: '0:06:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-09-20',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'Rower',
        distance: '7.2km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 460,
    },
    {
        date: '2020-09-22',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:13:30',
        restTime: '0:13:30',
        calories: 313,
    },
    {
        date: '2020-09-23',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '2.1km',
        workTime: '0:07:17',
        restTime: '7:30:00',
        calories: 164,
    },
    {
        date: '2020-09-24',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '2.2km',
        workTime: '0:09:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-09-25',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.2km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 422,
    },
    {
        date: '2020-09-29',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.3km',
        workTime: '0:15:00',
        restTime: '0:10:00',
        calories: 326,
    },
    {
        date: '2020-09-30',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '3.9km',
        workTime: '0:16:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-01',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.1km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 497,
    },
    {
        date: '2020-10-03',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '3.7km',
        workTime: '0:15:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-04',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.4km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 608,
    },
    {
        date: '2020-10-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'SkiErg',
        distance: '4km',
        workTime: '0:15:00',
        restTime: '0:15:00',
        calories: 272,
    },
    {
        date: '2020-10-07',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '21km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 576,
    },
    {
        date: '2020-10-09',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '2.5k',
        workTime: '0:08:00',
        restTime: '0:16:00',
        calories: 210,
    },
    {
        date: '2020-10-10',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '5.8km',
        workTime: '0:12:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-11',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '5.5km',
        workTime: '0:12:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-13',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '6.2km',
        workTime: '0:11:00',
        restTime: '0:11:00',
        calories: 237,
    },
    {
        date: '2020-10-17',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '7.3km',
        workTime: '0:16:00',
        restTime: '0:00:00',
        calories: 219,
    },
    {
        date: '2020-10-18',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '4.9km',
        workTime: '0:10:00',
        restTime: '0:00:00',
        calories: 154,
    },
    {
        date: '2020-10-20',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.8km',
        workTime: '0:18:00',
        restTime: '0:06:00',
        calories: 343,
    },
    {
        date: '2020-10-21',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '11.9km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 388,
    },
    {
        date: '2020-10-23',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '17km',
        workTime: '0:35:00',
        restTime: '0:00:00',
        calories: 542,
    },
    {
        date: '2020-10-24',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:15:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-25',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: '4.6km',
        workTime: '0:10:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-10-27',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '14.9km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 489,
    },
    {
        date: '2020-10-28',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:09:00',
        restTime: '0:10:00',
        calories: 0,
    },
    {
        date: '2020-10-30',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: '6.8km',
        workTime: '0:12:00',
        restTime: '0:12:00',
        calories: 263,
    },
    {
        date: '2020-10-31',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '4.8km',
        workTime: '0:10:00',
        restTime: '0:00:00',
        calories: 150,
    },
    {
        date: '2020-11-01',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'BikeErg',
        distance: '11.9km',
        workTime: '0:20:00',
        restTime: '0:04:00',
        calories: 385,
    },
    {
        date: '2020-11-03',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '19.3km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 612,
    },
    {
        date: '2020-11-04',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '17.6km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 568,
    },
    {
        date: '2020-11-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '1.9km',
        workTime: '0:06:00',
        restTime: '0:12:00',
        calories: 171,
    },
    {
        date: '2020-11-07',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '8.7km',
        workTime: '0:18:00',
        restTime: '0:00:00',
        calories: 278,
    },
    {
        date: '2020-11-08',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'BikeErg',
        distance: '16.0km',
        workTime: '0:32:00',
        restTime: '0:00:00',
        calories: 529,
    },
    {
        date: '2020-11-10',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.5km',
        workTime: '0:15:00',
        restTime: '0:15:00',
        calories: 376,
    },
    {
        date: '2020-11-11',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '20.4km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 653,
    },
    {
        date: '2020-11-13',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '4.8km',
        workTime: '0:08:15',
        restTime: '0:11:00',
        calories: 188,
    },
    {
        date: '2020-11-14',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '6.0km',
        workTime: '0:12:30',
        restTime: '0:00:00',
        calories: 191,
    },
    {
        date: '2020-11-15',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: '13.4km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 367,
    },
    {
        date: '2020-11-17',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.8km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 697,
    },
    {
        date: '2020-11-18',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '3.5km',
        workTime: '0:12:00',
        restTime: '0:12:00',
        calories: 277,
    },
    {
        date: '2020-11-20',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '11.8km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 381,
    },
    {
        date: '2020-11-21',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:12:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-11-22',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: '0:00:00',
        workTime: '0:06:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-11-24',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.1km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 417,
    },
    {
        date: '2020-11-25',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '2.48km',
        workTime: '0:09:00',
        restTime: '0:09:00',
        calories: 0,
    },
    {
        date: '2020-11-27',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.8km',
        workTime: '0:17:30',
        restTime: '0:10:00',
        calories: 347,
    },
    {
        date: '2020-11-28',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '5.7km',
        workTime: '0:12:00',
        restTime: '0:00:00',
        calories: 178,
    },
    {
        date: '2020-11-29',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: '13.0km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 355,
    },
    {
        date: '2020-11-30',
        phase: 'Cyborg',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 707,
    },
    {
        date: '2020-12-02',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.2km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 509,
    },
    {
        date: '2020-12-05',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'AirDyne',
        distance: '4.0km',
        workTime: '0:08:00',
        restTime: '0:00:00',
        calories: 91,
    },
    {
        date: '2020-12-06',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '2.7km',
        workTime: '0:09:00',
        restTime: '0:09:00',
        calories: 218,
    },
    {
        date: '2020-12-08',
        phase: 'Cyborg',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '20.3km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 648,
    },
    {
        date: '2020-12-09',
        phase: 'Cyborg',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '2.6km',
        workTime: '0:08:00',
        restTime: '0:16:00',
        calories: 229,
    },
    {
        date: '2020-12-16',
        phase: 'Cyborg',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '6.7km',
        workTime: '0:12:00',
        restTime: '0:12:00',
        calories: 250,
    },
    {
        date: '2020-12-17',
        phase: 'Cyborg',
        theme: 'Flux Stages',
        apparatus: 'AirDyne',
        distance: '0:00:00',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 459,
    },
    {
        date: '2020-12-19',
        phase: 'Cyborg',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '5.8km',
        workTime: '0:12:00',
        restTime: '0:00:00',
        calories: 0,
    },
    {
        date: '2020-12-20',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '17.0km',
        workTime: '0:35:00',
        restTime: '0:00:00',
        calories: 545,
    },
    {
        date: '2020-12-22',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.9km',
        workTime: '0:14:04',
        restTime: '0:08:00',
        calories: 217,
    },
    {
        date: '2020-12-23',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '14.8km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 411,
    },
    {
        date: '2020-12-26',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '3.5km',
        workTime: '0:12:00',
        restTime: '0:12:00',
        calories: 279,
    },
    {
        date: '2020-12-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: '6.3km',
        workTime: '0:11:20',
        restTime: '0:04:40',
        calories: 240,
    },
    {
        date: '2020-12-28',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'AirDyne',
        distance: '11.0km',
        workTime: '0:13:00',
        restTime: '0:06:00',
        calories: 248,
    },
    {
        date: '2020-12-30',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '2.0km',
        workTime: '0:06:25',
        restTime: '0:11:00',
        calories: 166,
    },
    {
        date: '2021-01-01',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '10.6km',
        workTime: '0:20:00',
        restTime: '0:05:00',
        calories: 374,
    },
    {
        date: '2021-01-01',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '20.3km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 567,
    },
    {
        date: '2021-01-02',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.4km',
        workTime: '0:12:00',
        restTime: '0:11:30',
        calories: 255,
    },
    {
        date: '2021-01-03',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.1km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 500,
    },
    {
        date: '2021-01-05',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:12:51',
        restTime: '0:11:00',
        calories: 279,
    },
    {
        date: '2021-01-08',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '4.6km',
        workTime: '0:16:21',
        restTime: '0:11:45',
        calories: 344,
    },
    {
        date: '2021-01-09',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '21.1km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 581,
    },
    {
        date: '2021-01-10',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: '12.7km',
        workTime: '0:24:00',
        restTime: '0:06:00',
        calories: 450,
    },
    {
        date: '2021-01-11',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '6.2km',
        workTime: '0:12:00',
        restTime: '0:06:00',
        calories: 232,
    },
    {
        date: '2021-01-12',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: '9.0km',
        workTime: '0:17:00',
        restTime: '0:08:00',
        calories: 317,
    },
    {
        date: '2021-01-14',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.8km',
        workTime: '0:15:00',
        restTime: '0:08:00',
        calories: 285,
    },
    {
        date: '2021-01-16',
        phase: 'Hybrid',
        theme: 'Cyborg',
        apparatus: 'BikeErg',
        distance: '1.9km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 60,
    },
    {
        date: '2021-01-17',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.7km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 693,
    },
    {
        date: '2021-01-19',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '16.1km',
        workTime: '0:33:00',
        restTime: '0:00:00',
        calories: 521,
    },
    {
        date: '2021-01-20',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.9km',
        workTime: '0:13:45',
        restTime: '0:08:45',
        calories: 308,
    },
    {
        date: '2021-01-23',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '6.5km',
        workTime: '0:24:00',
        restTime: '0:08:00',
        calories: 465,
    },
    {
        date: '2021-01-24',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'BikeErg',
        distance: '4.0km',
        workTime: '0:06:40',
        restTime: '0:07:30',
        calories: 166,
    },
    {
        date: '2021-01-25',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.2km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 508,
    },
    {
        date: '2021-01-26',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.9km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 705,
    },
    {
        date: '2021-01-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:10:30',
        restTime: '0:08:30',
        calories: 233,
    },
    {
        date: '2021-01-28',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '2.5km',
        workTime: '0:08:15',
        restTime: '0:08:15',
        calories: 206,
    },
    {
        date: '2021-01-29',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.8km',
        workTime: '0:45:04',
        restTime: '0:00:00',
        calories: 700,
    },
    {
        date: '2021-02-01',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:12:40',
        restTime: '0:09:45',
        calories: 270,
    },
    {
        date: '2021-02-02',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '19.9km',
        workTime: '0:39:00',
        restTime: '0:00:00',
        calories: 563,
    },
    {
        date: '2021-02-03',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '2.3km',
        workTime: '0:08:00',
        restTime: '0:07:15',
        calories: 173,
    },
    {
        date: '2021-02-05',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '5.3km',
        workTime: '0:20:00',
        restTime: '0:05:00',
        calories: 374,
    },
    {
        date: '2021-02-06',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '25.3km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 420,
    },
    {
        date: '2021-02-08',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'AirDyne',
        distance: '15.7km',
        workTime: '0:12:00',
        restTime: '0:08:00',
        calories: 260,
    },
    {
        date: '2021-02-09',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '21.3km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 596,
    },
    {
        date: '2021-02-10',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.1km',
        workTime: '0:10:30',
        restTime: '0:13:30',
        calories: 249,
    },
    {
        date: '2021-02-13',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '2.3km',
        workTime: '0:08:00',
        restTime: '0:08:00',
        calories: 174,
    },
    {
        date: '2021-02-15',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '2.5km',
        workTime: '0:08:40',
        restTime: '0:09:30',
        calories: 201,
    },
    {
        date: '2021-02-17',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.6km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 624,
    },
    {
        date: '2021-02-19',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:14:00',
        restTime: '0:15:00',
        calories: 317,
    },
    {
        date: '2021-02-20',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: '11.0km',
        workTime: '0:21:00',
        restTime: '0:03:00',
        calories: 385,
    },
    {
        date: '2021-02-21',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.2km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 510,
    },
    {
        date: '2021-02-23',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:12:40',
        restTime: '0:08:00',
        calories: 272,
    },
    {
        date: '2021-02-25',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.9km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 708,
    },
    {
        date: '2021-02-26',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '19.7km',
        workTime: '0:39:00',
        restTime: '0:00:00',
        calories: 546,
    },
    {
        date: '2021-02-27',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '5.4km',
        workTime: '0:19:30',
        restTime: '0:11:45',
        calories: 405,
    },
    {
        date: '2021-02-28',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '7.8km',
        workTime: '0:14:36',
        restTime: '0:15:00',
        calories: 281,
    },
    {
        date: '2021-03-03',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.4km',
        workTime: '0:12:00',
        restTime: '0:13:30',
        calories: 263,
    },
    {
        date: '2021-03-05',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '2.8km',
        workTime: '0:09:20',
        restTime: '0:12:45',
        calories: 227,
    },
    {
        date: '2021-03-06',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.8km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 698,
    },
    {
        date: '2021-03-07',
        phase: 'Hybrid',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '6.5km',
        workTime: '0:24:00',
        restTime: '0:12:00',
        calories: 467,
    },
    {
        date: '2021-03-08',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '18.1km',
        workTime: '0:36:00',
        restTime: '0:00:00',
        calories: 500,
    },
    {
        date: '2021-03-10',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.3km',
        workTime: '0:11:30',
        restTime: '0:08:00',
        calories: 248,
    },
    {
        date: '2021-03-12',
        phase: 'Hybrid',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '21.2km',
        workTime: '0:42:00',
        restTime: '0:00:00',
        calories: 587,
    },
    {
        date: '2021-03-14',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:12:20',
        restTime: '0:11:15',
        calories: 277,
    },
    {
        date: '2021-03-15',
        phase: 'Hybrid',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.9km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 701,
    },
    {
        date: '2021-03-17',
        phase: 'Hybrid',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '3.2km',
        workTime: '0:12:00',
        restTime: '0:06:00',
        calories: 239,
    },
    {
        date: '2021-03-21',
        phase: 'Hybrid',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '5.2km',
        workTime: '0:19:00',
        restTime: '0:11:30',
        calories: 386,
    },
    {
        date: '2021-03-23',
        phase: 'Devour',
        theme: 'Time Trial',
        apparatus: 'Rower',
        distance: '2.8km',
        workTime: '0:10:00',
        restTime: '0:00:00',
        calories: 203,
    },
    {
        date: '2021-03-24',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.5km',
        workTime: '0:18:00',
        restTime: '0:04:00',
        calories: 336,
    },
    {
        date: '2021-03-26',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22.2km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 723,
    },
    {
        date: '2021-03-27',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.3km',
        workTime: '0:16:00',
        restTime: '0:08:00',
        calories: 309,
    },
    {
        date: '2021-03-30',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.6km',
        workTime: '0:19:30',
        restTime: '0:06:00',
        calories: 295,
    },
    {
        date: '2021-04-02',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:15:00',
        restTime: '0:02:30',
        calories: 290,
    },
    {
        date: '2021-04-03',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.1km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 544,
    },
    {
        date: '2021-04-04',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '5.5km',
        workTime: '0:20:00',
        restTime: '0:10:00',
        calories: 403,
    },
    {
        date: '2021-04-05',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '13.0km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 352,
    },
    {
        date: '2021-04-07',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.8km',
        workTime: '0:26:00',
        restTime: '0:04:00',
        calories: 483,
    },
    {
        date: '2021-04-08',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.1km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 417,
    },
    {
        date: '2021-04-09',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '5.3km',
        workTime: '0:20:00',
        restTime: '0:04:00',
        calories: 381,
    },
    {
        date: '2021-04-10',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.9km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 707,
    },
    {
        date: '2021-04-13',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.8km',
        workTime: '0:18:00',
        restTime: '0:06:00',
        calories: 355,
    },
    {
        date: '2021-04-14',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.8km',
        workTime: '0:18:00',
        restTime: '0:04:00',
        calories: 345,
    },
    {
        date: '2021-04-15',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '12.9km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 349,
    },
    {
        date: '2021-04-16',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '2.8km',
        workTime: '0:10:30',
        restTime: '0:01:30',
        calories: 198,
    },
    {
        date: '2021-04-17',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '20.1km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 555,
    },
    {
        date: '2021-04-18',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '5.3km',
        workTime: '0:20:00',
        restTime: '0:04:00',
        calories: 368,
    },
    {
        date: '2021-04-21',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '2.5km',
        workTime: '0:09:05',
        restTime: '0:02:00',
        calories: 181,
    },
    {
        date: '2021-04-22',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 413,
    },
    {
        date: '2021-04-23',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '3.8km',
        workTime: '0:13:50',
        restTime: '0:10:00',
        calories: 282,
    },
    {
        date: '2021-04-24',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.6km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 619,
    },
    {
        date: '2021-04-26',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'BikeErg',
        distance: '8.4km',
        workTime: '0:16:00',
        restTime: '0:08:00',
        calories: 293,
    },
    {
        date: '2021-04-27',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '5.3km',
        workTime: '0:21:00',
        restTime: '0:06:00',
        calories: 381,
    },
    {
        date: '2021-04-29',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.0km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 554,
    },
    {
        date: '2021-04-30',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '6.3km',
        workTime: '0:27:30',
        restTime: '0:05:00',
        calories: 380,
    },
    {
        date: '2021-05-01',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '5.5km',
        workTime: '0:20:00',
        restTime: '0:10:00',
        calories: 408,
    },
    {
        date: '2021-05-02',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'BikeErg',
        distance: '12.0km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 401,
    },
    {
        date: '2021-05-04',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '6.0km',
        workTime: '0:24:00',
        restTime: '0:03:00',
        calories: 420,
    },
    {
        date: '2021-05-05',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.2km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 426,
    },
    {
        date: '2021-05-06',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.4km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 603,
    },
    {
        date: '2021-05-07',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '5.1km',
        workTime: '0:20:00',
        restTime: '0:08:00',
        calories: 379,
    },
    {
        date: '2021-05-08',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '6.4km',
        workTime: '0:24:00',
        restTime: '0:08:00',
        calories: 451,
    },
    {
        date: '2021-05-11',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '5.0km',
        workTime: '0:20:00',
        restTime: '0:04:00',
        calories: 343,
    },
    {
        date: '2021-05-12',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '4.2km',
        workTime: '0:16:15',
        restTime: '0:03:45',
        calories: 294,
    },
    {
        date: '2021-05-14',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '12.5km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 355,
    },
    {
        date: '2021-05-18',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.1km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 556,
    },
    {
        date: '2021-05-19',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '3.7km',
        workTime: '0:13:30',
        restTime: '0:04:30',
        calories: 274,
    },
    {
        date: '2021-05-21',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '7.6km',
        workTime: '0:39:00',
        restTime: '0:06:00',
        calories: 538,
    },
    {
        date: '2021-05-22',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.1km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 555,
    },
    {
        date: '2021-05-23',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:15:00',
        restTime: '0:05:00',
        calories: 291,
    },
    {
        date: '2021-05-24',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22.1km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 720,
    },
    {
        date: '2021-05-25',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.9km',
        workTime: '0:18:00',
        restTime: '0:06:00',
        calories: 354,
    },
    {
        date: '2021-05-28',
        phase: 'Devour',
        theme: 'Descending Devour',
        apparatus: 'Rower',
        distance: '3.1km',
        workTime: '0:12:00',
        restTime: '0:05:00',
        calories: 0,
    },
    {
        date: '2021-05-29',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '5.0km',
        workTime: '0:18:00',
        restTime: '0:12:00',
        calories: 366,
    },
    {
        date: '2021-05-30',
        phase: 'Devour',
        theme: 'Ascending Devour',
        apparatus: 'Rower',
        distance: '4.9km',
        workTime: '0:18:00',
        restTime: '0:04:00',
        calories: 361,
    },
    {
        date: '2021-05-31',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.1km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 420,
    },
    {
        date: '2021-06-02',
        phase: 'Devour',
        theme: 'Descending Devour',
        apparatus: 'Rower',
        distance: '3.2km',
        workTime: '0:12:00',
        restTime: '0:06:00',
        calories: 235,
    },
    {
        date: '2021-06-04',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '8.3km',
        workTime: '0:16:00',
        restTime: '0:00:00',
        calories: 239,
    },
    {
        date: '2021-06-05',
        phase: 'Devour',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '17.2km',
        workTime: '0:35:00',
        restTime: '0:00:00',
        calories: 555,
    },
    {
        date: '2021-06-06',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.5km',
        workTime: '0:15:00',
        restTime: '0:15:00',
        calories: 372,
    },
    {
        date: '2021-06-07',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '20.0km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 656,
    },
    {
        date: '2021-06-08',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '5.1km',
        workTime: '0:19:30',
        restTime: '0:01:30',
        calories: 360,
    },
    {
        date: '2021-06-10',
        phase: 'Devour',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '15.0km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 418,
    },
    {
        date: '2021-06-12',
        phase: 'Devour',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '4.7km',
        workTime: '0:17:30',
        restTime: '0:02:30',
        calories: 336,
    },
    {
        date: '2021-06-15',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '3.3km',
        workTime: '0:12:00',
        restTime: '0:05:15',
        calories: 244,
    },
    {
        date: '2021-06-16',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '5.3km',
        workTime: '0:19:35',
        restTime: '0:06:00',
        calories: 382,
    },
    {
        date: '2021-06-18',
        phase: 'Devour',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '10.2km',
        workTime: '0:20:00',
        restTime: '0:00:00',
        calories: 289,
    },
    {
        date: '2021-06-21',
        phase: 'Devour',
        theme: 'Devour',
        apparatus: 'Rower',
        distance: '2.2km',
        workTime: '0:07:59',
        restTime: '0:03:00',
        calories: 93,
    },
    {
        date: '2021-06-23',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.3km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 601,
    },
    {
        date: '2021-06-25',
        phase: 'Infinity',
        theme: 'Time Trial',
        apparatus: 'Rower',
        distance: '2.8km',
        workTime: '0:10:00',
        restTime: '0:00:00',
        calories: 205,
    },
    {
        date: '2021-06-26',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '12.4km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 355,
    },
    {
        date: '2021-07-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '1km',
        workTime: '0:04:05',
        restTime: '0:00:00',
        calories: 77,
    },
    {
        date: '2021-07-02',
        phase: 'Infinity',
        theme: 'Intervals',
        apparatus: 'Rower',
        distance: '12.6km',
        workTime: '0:24:00',
        restTime: '0:08:00',
        calories: 443,
    },
    {
        date: '2021-07-03',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '5.5km',
        workTime: '0:21:00',
        restTime: '0:03:15',
        calories: 243,
    },
    {
        date: '2021-07-04',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.3km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 600,
    },
    {
        date: '2021-07-07',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '5.4km',
        workTime: '0:20:00',
        restTime: '0:07:30',
        calories: 324,
    },
    {
        date: '2021-07-08',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:05:00',
        restTime: '0:05:00',
        calories: 126,
    },
    {
        date: '2021-07-10',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.4km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 579,
    },
    {
        date: '2021-07-12',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.3km',
        workTime: '0:16:22',
        restTime: '0:03:00',
        calories: 241,
    },
    {
        date: '2021-07-13',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '21.8km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 698,
    },
    {
        date: '2021-07-14',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:14:03',
        restTime: '0:12:00',
        calories: 264,
    },
    {
        date: '2021-07-15',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '12.5km',
        workTime: '0:24:00',
        restTime: '0:00:00',
        calories: 367,
    },
    {
        date: '2021-07-16',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22.3km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 732,
    },
    {
        date: '2021-07-17',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '9.0km',
        workTime: '0:16:50',
        restTime: '0:03:15',
        calories: 316,
    },
    {
        date: '2021-07-18',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.2km',
        workTime: '0:13:00',
        restTime: '0:07:45',
        calories: 244,
    },
    {
        date: '2021-07-20',
        phase: 'Infinity',
        theme: 'Intervals',
        apparatus: 'SkiErg',
        distance: '3.6km',
        workTime: '0:13:30',
        restTime: '0:13:30',
        calories: 240,
    },
    {
        date: '2021-07-22',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:14:00',
        restTime: '0:14:00',
        calories: 317,
    },
    {
        date: '2021-07-24',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '20.0km',
        workTime: '0:40:00',
        restTime: '0:00:00',
        calories: 565,
    },
    {
        date: '2021-07-25',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '5.0km',
        workTime: '0:22:30',
        restTime: '0:07:45',
        calories: 294,
    },
    {
        date: '2021-07-29',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '5.0km',
        workTime: '0:26:00',
        restTime: '0:07:30',
        calories: 391,
    },
    {
        date: '2021-08-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.9km',
        workTime: '0:14:00',
        restTime: '0:04:45',
        calories: 296,
    },
    {
        date: '2021-08-04',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.2km',
        workTime: '0:18:30',
        restTime: '0:07:30',
        calories: 321,
    },
    {
        date: '2021-08-05',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '1.7km',
        workTime: '0:06:00',
        restTime: '0:06:00',
        calories: 128,
    },
    {
        date: '2021-08-06',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.5km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 614,
    },
    {
        date: '2021-08-08',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '2.6km',
        workTime: '0:09:00',
        restTime: '0:03:00',
        calories: 198,
    },
    {
        date: '2021-08-09',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '9.2km',
        workTime: '0:18:00',
        restTime: '0:00:00',
        calories: 266,
    },
    {
        date: '2021-08-11',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:15:45',
        restTime: '0:03:45',
        calories: 293,
    },
    {
        date: '2021-08-13',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '23.0km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 651,
    },
    {
        date: '2021-08-15',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.0km',
        workTime: '0:14:00',
        restTime: '0:09:30',
        calories: 309,
    },
    {
        date: '2021-08-17',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'AirDyne',
        distance: '25.3km',
        workTime: '0:50:00',
        restTime: '0:00:00',
        calories: 703,
    },
    {
        date: '2021-08-18',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'Rower',
        distance: '8.0km',
        workTime: '0:31:30',
        restTime: '0:10:30',
        calories: 545,
    },
    {
        date: '2021-08-19',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '23.0km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 645,
    },
    {
        date: '2021-08-21',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.7km',
        workTime: '0:13:00',
        restTime: '0:06:45',
        calories: 291,
    },
    {
        date: '2021-08-22',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '3.6km',
        workTime: '0:12:40',
        restTime: '0:08:00',
        calories: 273,
    },
    {
        date: '2021-08-24',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'AirDyne',
        distance: '16.5km',
        workTime: '0:32:00',
        restTime: '0:00:00',
        calories: 472,
    },
    {
        date: '2021-08-25',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.8km',
        workTime: '0:13:30',
        restTime: '0:06:45',
        calories: 292,
    },
    {
        date: '2021-08-26',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.8km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 632,
    },
    {
        date: '2021-08-29',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '22.5km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 613,
    },
    {
        date: '2021-08-30',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:16:01',
        restTime: '0:03:00',
        calories: 154,
    },
    {
        date: '2021-08-31',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '4.1km',
        workTime: '0:07:00',
        restTime: '0:07:00',
        calories: 165,
    },
    {
        date: '2021-09-01',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.7km',
        workTime: '0:22:00',
        restTime: '0:03:45',
        calories: 358,
    },
    {
        date: '2021-09-02',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'AirDyne',
        distance: '16.4km',
        workTime: '0:32:00',
        restTime: '0:00:00',
        calories: 462,
    },
    {
        date: '2021-09-04',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22.1km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 619,
    },
    {
        date: '2021-09-06',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.7km',
        workTime: '0:20:00',
        restTime: '0:02:45',
        calories: 278,
    },
    {
        date: '2021-09-07',
        phase: 'Infinity',
        theme: 'Hybrid',
        apparatus: 'Rower',
        distance: '5.5km',
        workTime: '0:19:30',
        restTime: '0:12:45',
        calories: 414,
    },
    {
        date: '2021-09-09',
        phase: 'Infinity',
        theme: 'Polarisation',
        apparatus: 'BikeErg',
        distance: '27.4km',
        workTime: '0:55:00',
        restTime: '0:00:00',
        calories: 907,
    },
    {
        date: '2021-09-11',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '22.7km',
        workTime: '0:45:00',
        restTime: '0:00:00',
        calories: 759,
    },
    {
        date: '2021-09-14',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '3.0km',
        workTime: '0:15:00',
        restTime: '0:06:45',
        calories: 241,
    },
    {
        date: '2021-09-15',
        phase: 'Infinity',
        theme: 'Ascending',
        apparatus: 'BikeErg',
        distance: '3.6km',
        workTime: '0:13:00',
        restTime: '0:06:30',
        calories: 259,
    },
    {
        date: '2021-09-16',
        phase: 'Infinity',
        theme: 'Endurance',
        apparatus: 'BikeErg',
        distance: '7.6km',
        workTime: '0:30:00',
        restTime: '0:00:00',
        calories: 513,
    },
    {
        date: '2021-09-17',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '4.3km',
        workTime: '0:21:19',
        restTime: '0:07:30',
        calories: 237,
    },
    {
        date: '2021-09-19',
        phase: 'Infinity',
        theme: 'Flux',
        apparatus: 'BikeErg',
        distance: '12.1km',
        workTime: '0:24:03',
        restTime: '0:00:00',
        calories: 405,
    },
    {
        date: '2021-09-23',
        phase: 'Infinity',
        theme: 'Infinity',
        apparatus: 'Rower',
        distance: '2.5km',
        workTime: '0:10:00',
        restTime: '0:05:45',
        calories: 196,
    },
];
